"""Investment Memo page — rendered markdown with export."""

import streamlit as st

from dashboard.theme import COLORS
from dashboard.components.cards import section_header
from dashboard.data_loader import load_memo


def render() -> None:
    memo = load_memo()

    if not memo:
        st.warning("No investment memo found. Run `python -m src.main --run memo` first.")
        return

    section_header("Investment Memo", "Auto-generated by the analytical pipeline")

    # Export button
    col1, col2, _ = st.columns([1, 1, 3])
    with col1:
        st.download_button(
            label="Download as Markdown",
            data=memo,
            file_name="vero_capital_investment_memo.md",
            mime="text/markdown",
        )
    with col2:
        # Generate a simple HTML version for "PDF-like" export
        html_content = f"""<!DOCTYPE html>
<html><head>
<meta charset="utf-8">
<style>
    body {{ font-family: 'Georgia', serif; max-width: 800px; margin: 40px auto; padding: 0 20px;
           color: #1a1a1a; line-height: 1.7; font-size: 14px; }}
    h1 {{ color: #0F766E; border-bottom: 2px solid #0F766E; padding-bottom: 10px; }}
    h2 {{ color: #0D9488; margin-top: 30px; }}
    h3 {{ color: #334155; }}
    table {{ border-collapse: collapse; width: 100%; margin: 16px 0; }}
    th, td {{ border: 1px solid #ddd; padding: 8px 12px; text-align: left; }}
    th {{ background: #f1f5f9; font-weight: 600; }}
    code {{ background: #f1f5f9; padding: 2px 6px; border-radius: 3px; }}
    hr {{ border: none; border-top: 1px solid #e2e8f0; margin: 24px 0; }}
</style>
</head><body>
{memo}
</body></html>"""
        st.download_button(
            label="Download as HTML",
            data=html_content,
            file_name="vero_capital_investment_memo.html",
            mime="text/html",
        )

    st.markdown("<div style='height:16px'></div>", unsafe_allow_html=True)

    # Render the memo
    st.markdown(f"""
    <div style="
        background:{COLORS['bg_card']};
        border:1px solid {COLORS['border']};
        border-radius:8px;
        padding:32px 40px;
        line-height:1.8;
        font-size:0.95rem;
    ">
    """, unsafe_allow_html=True)

    st.markdown(memo)

    st.markdown("</div>", unsafe_allow_html=True)
